### ISSUE TITLE
cannot install logging-go using go get -u github.com/hellofresh/logging-go

### ISSUE THREAD

**Issue by rjtch** [hellofresh/logging-go#10]
Hello guys,

i'm coding a sample resfulapi in golang and i wanted that package for logging. But when a try to install it using "go get -u github.com/hellofresh/logging-go" i always get this error 

# github.com/hellofresh/logging-go
hellofresh/logging-go/hooks.go:27:15: undefined: logrustash.NewHookWithConn
hellofresh/logging-go/hooks.go:27:57: formatter.Type undefined (type *logrustash.LogstashFormatter has no field or method Type)
hellofresh/logging-go/hooks.go:32:29: formatter.TimestampFormat undefined (type *logrustash.LogstashFormatter has no field or method TimestampFormat)
hellofresh/logging-go/log_config.go:163:43: unknown field 'Type' in struct literal of type logrustash.LogstashFormatter
hellofresh/logging-go/log_config.go:163:74: unknown field 'TimestampFormat' in struct literal of type logrustash.LogstashFormatter

Can someone tell me what i suppose to do to get this project install in my computer????

**Comment by vgarvardt** [comment]
@rjtch what version of `github.com/bshuster-repo/logrus-logstash-hook` do you have installed? Library currently relies on `0.4.1` and does not work with `1.0-beta` - https://github.com/hellofresh/logging-go/blob/master/Gopkg.toml#L24-L26
